### ISSUE TITLE
net-im/zoom-bin: permalinks for upstream binary package versions

### ISSUE THREAD

**Issue by ALTracer** [SpiderX/portage-overlay#14]
**SRC_URI always fetches latest zoom_amd64.deb which may be newer than ebuild**

At the date of commiting the ebuild `SRC_URI` returned correct current stable package version.
As soon as upstream pushes an update ebuilds start failing due to length and checksum mismatches even though Portage tries to download by same URI. This works for static mirrors, distfiles and repositories, but doesn't work for 3rdparty dynamic binary download links.

For example,
https://github.com/SpiderX/portage-overlay/blob/a04233ffc9a7065356cc9ab078dffd1b81fbf97a/net-im/zoom-bin/zoom-bin-3.5.361976.0301.ebuild#L14
should lead to
https://d11yldzmag5yn.cloudfront.net/prod/3.5.361976.0301/zoom_amd64.deb
but today it leads to current version, which is
https://d11yldzmag5yn.cloudfront.net/prod/3.5.383291.0407/zoom_amd64.deb

Please consider either bumping the version on par with upstream, or hosting a mirror with binary packages and determinate links.

**Comment by ALTracer** [comment]
Actually, check out the ebuild in [the official Gentoo repository](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-im/zoom/):
```
SRC_URI="amd64? ( https://zoom.us/client/${PV}/${PN}_x86_64.tar.xz -> ${P}_x86_64.tar.xz )
	x86? ( https://zoom.us/client/${PV}/${PN}_i686.tar.xz -> ${P}_i686.tar.xz )"
```
BTW, the current version seems to be 3.5.392530.0421 !
I used yours until they dropped direct libglvnd dependency in favor of virtual/opengl.
The issue is I cannot log into my Zoom account an my system -- kde-open5 refuses to run with the wild LD_LIBRARY_PATH because it depends on Qt5.14.1 on my running system but finds Qt5.9.5 from the binary package first. Perharps `patchelf` or `bbe` helps. It still authorizes me when I join meetings from Chrome browser where I'm logged in beforehand.

**Comment by SpiderX** [comment]
@ALTracer Thanks, I updated ebuild. It now uses URL provided by you.
