### ISSUE TITLE
bump postgrest

### ISSUE THREAD

**Issue by megacherry** [SpiderX/portage-overlay#166]
hi @SpiderX ,

thanks for your excellent work. is it possible to update postgrest to the current version v12? i am currently using it as a binary.

i hope here is the right place.

best regards
Andy

**Comment by SpiderX** [comment]
Hi.
Yes, it is possible and yes, it is the right place.
v12 added in [this](https://github.com/SpiderX/portage-overlay/commit/4121bc89eccc52331b8bf70a9b8934a52fc66c1e) commit.
