### ISSUE TITLE
media-sound/plexamp runtime error

### ISSUE THREAD

**Issue by WillPower3309** [SpiderX/portage-overlay#18]
```
xdg-mime: application argument missing
Try 'xdg-mime --help' for more information.
Couldn't install shortcut for Shift+CommandOrControl+Space.
Couldn't install shortcut for Shift+Command+Control+Option+0.
Couldn't install shortcut for Shift+Command+Control+Option+1.
Couldn't install shortcut for Shift+Command+Control+Option+2.
Couldn't install shortcut for Shift+Command+Control+Option+3.
Couldn't install shortcut for Shift+Command+Control+Option+4.
Couldn't install shortcut for Shift+Command+Control+Option+5.
Couldn't install shortcut for Shift+CommandOrControl+Option+Right.
Couldn't install shortcut for CommandOrControl+Option+Up.
Couldn't install shortcut for CommandOrControl+Option+Down.
Couldn't install shortcut for Shift+Alt+Space.
Couldn't install shortcut for MediaPlayPause.
Couldn't install shortcut for MediaPreviousTrack.
Couldn't install shortcut for MediaNextTrack.
Started Media Service: false
Linux: Registering MPRIS service.
Linux: Error registering media services: Cannot find module 'abstract-socket'
Require stack:
- /opt/plexamp/resources/app.asar/node_modules/dbus-next/lib/connection.js
- /opt/plexamp/resources/app.asar/node_modules/dbus-next/index.js
- /opt/plexamp/resources/app.asar/main.js
-
```

compiled with no use flags

**Comment by SpiderX** [comment]
@WillPower3309 Hi, check [this](https://forums.plex.tv/t/plexamp-3-0-not-starting-on-arch-linux/575426/5) thread and try to run it with --disable-seccomp-filter-sandbox

**Comment by SpiderX** [comment]
@WillPower3309 Did it help?
I can't reproduce this issue on my system. But if it helps I can add use flag to disable seccomp in ebuild.

**Comment by WillPower3309** [comment]
Can confirm it works with `--disable-seccomp-filter-sandbox`

**Comment by SpiderX** [comment]
@WillPower3309 Thanks.
I added seccomp USE flag to the latest ebuild.
You can emerge it with USE="-seccomp" emerge -atv media-sound/plexamp
This will result in desktop file for plexamp will contain:

`Exec=plexamp --disable-seccomp-filter-sandbox`

**Comment by WillPower3309** [comment]
> @WillPower3309 Thanks.
> I added seccomp USE flag to the latest ebuild.
> You can emerge it with USE="-seccomp" emerge -atv media-sound/plexamp
> This will result in desktop file for plexamp will contain:
> 
> `Exec=plexamp --disable-seccomp-filter-sandbox`
> 

Thanks a ton man!
