### ISSUE TITLE
dev-ml/ocaml-mm: Inaccurate description?

### ISSUE THREAD

**Issue by Sophira** [SpiderX/portage-overlay#19]
The description for **dev-ml/ocaml-mm** reads "OCaml bindings to mm" (where "mm" presumably refers to dev-libs/mm, a shared memory abstraction library) but that doesn't seem to match up with the package has as dependencies, or how the [source repository](https://github.com/savonet/ocaml-mm) describes itself: "...a library dedicated to performing operations on multimedia contents: audio, video and MIDI."

I'm guessing this was an automatic scripted description, so I just wanted to let you know that it seems like it might be incorrect!

**Comment by SpiderX** [comment]
@Sophira Thank you.
I changed description to reflect what this ebuild is about more correctly.
