### ISSUE TITLE
media-radio/liquidsoap-1.3.7: USE flags "json" + "unicode" try to install blocking packages

### ISSUE THREAD

**Issue by Sophira** [SpiderX/portage-overlay#20]
When trying to install **media-radio/liquidsoap-1.3.7**, I enabled the USE flags "json" and "unicode". However, the implementation of these two USE Flags appears to make it such that they are incompatible:

* `USE="json"` depends on **dev-ml/yojson** (in the Gentoo repository), which depends on **dev-ml/jbuilder**.
* `USE="unicode"` depends on **>=dev-ml/camomile-1.0.2** (currently only in this repository), which depends on **>=dev-ml/dune-1.11.1** (2.1.0 is available/stable in the Gentoo repository).

Dune is actually the new name of the project previously known as Jbuilder (see [Gentoo bug #682782](https://bugs.gentoo.org/682782)) and as such **dev-ml/dune** has a hard block on **dev-ml/jbuilder** in its `RDEPEND`, which would be necessary for enabling the "json" USE flag.

I assume that there's a good reason for why Gentoo keep both packages around, but I couldn't tell you why. In any case, I figured you might want to know. Note that this hard block is in both the Gentoo version of **dev-ml/dune** and in the older version that you have in this repo.

**Comment by Sophira** [comment]
I've been having a lot of trouble trying to get liquidsoap's dependencies installed, unfortunately. I might open another issue about that. That might be in a few days though.

Are you able to install liquidsoap okay?

**Comment by SpiderX** [comment]
I do have liquidsoap 1.3.7 installed from this overlay, but it was installed in times corresponding ebuild was added into overlay.
All ebuilds in this overlay relies on portage tree which is constantly changes and sometimes these changes introduces issues like you had with jbuilder and dune.
Other type of issues is connected with the fact that ocaml support is far from good state in portage, this introduces some issues too. For example, I wasn't able build liquidsoap 1.4.x several months ago. But as I see things changes in a good way.

So, yes, open issues to address problems you are observing and I will try to resolve them.
