### ISSUE TITLE
app-emulation/looking-glass is not building

### ISSUE THREAD

**Issue by grepwood** [SpiderX/portage-overlay#5]
Check https://github.com/SpiderX/portage-overlay/issues/4#issuecomment-427984509

**Comment by grepwood** [comment]
Here's a fix: remove the following line from ebuild:
```
	-e '/DBUILD_VERSION/d' \
```

**Comment by SpiderX** [comment]
@grepwood Thanks!
I replaced BUILD_VERSION with a version for ebuild rather than removing it like it was before.
