### ISSUE TITLE
Missing dependency for twinkle

### ISSUE THREAD

**Issue by chriham** [SpiderX/portage-overlay#92]
I tried to emerge net-voip/twinkle but getting this error:

> emerge: there are no ebuilds to satisfy "dev-cpp/commoncpp2".
(dependency required by "net-voip/twinkle-1.10.2::nest" [ebuild])
(dependency required by "twinkle" [argument])

Maybe commoncpp2 is no longer provided by default portage overlay?

**Comment by SpiderX** [comment]
Fixed in [this](https://github.com/SpiderX/portage-overlay/commit/787b1214813d78a77aee757d11efe09794a32099) commit.
